language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    - pip install toolz==0.10.0
    - pip install pytest

install:
    - python setup.py build_ext --inplace --without-cython

# commands to run tests
script:
    - nosetests --with-doctest cytoolz
    # For convenience, make sure simple test commands work
    - py.test
    - nosetests

notifications:
  email: false
