language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
    include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
    - pip install git+https://github.com/pytoolz/toolz.git
    - pip install cython pytest

install:
    - python setup.py build_ext --inplace --with-cython

# commands to run tests
script:
    - nosetests --with-doctest cytoolz
    # For convenience, make sure simple test commands work
    - py.test
    - nosetests
    # Make sure we can cimport cytoolz
    - echo 'cimport cytoolz ; from cytoolz.functoolz cimport memoize' > try_cimport_cytoolz.pyx
    - cythonize -i try_cimport_cytoolz.pyx
    - python -c 'import try_cimport_cytoolz'

notifications:
  email: false
